"use client";
import localFont from "next/font/local";
import "./globals.css";
import StoreProvider from "../lib/redux/StoreProvider";
import Head from "next/head";
import { useEffect, useState } from "react";
import Image from "next/image";
import { motion } from "framer-motion";

const geistSans = localFont({
	src: "../components/fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "../components/fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

// export const metadata: Metadata = {
// 	title: "Sakindah Wedding Platform",
// 	description: "Generated by create next app",
// 	icons: "/logo/PNG/tertiary_1.png",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const [isLoaded, setIsLoaded] = useState(false);

	useEffect(() => {
		setIsLoaded(true);
	}, []);
	if (!isLoaded) {
		return (
			<div className='flex justify-center items-center h-screen'>
				<div className='text-center text-primary'>
					Sebentar ya...
					<motion.div
						className='m-auto'
						animate={{
							rotate: [0, 180],
						}}
						transition={{
							duration: 2,
							repeat: Infinity,
							ease: "easeInOut",
						}}>
						<Image
							src='/logo/png/tertiary_1.png'
							alt='loader'
							width={150}
							height={150}
						/>
					</motion.div>
				</div>
			</div>
		);
	}
	return (
		<html lang='id'>
			<Head>
				<title>Sakinah Wedding Platform</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='shortcut icon' href='/logo/PNG/tertiary_1.png' />
			</Head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<div className='min-h-screen'>
					<StoreProvider>{children}</StoreProvider>
				</div>
			</body>
		</html>
	);
}
